openapi: 3.0.1
info:
  title: ePI-read
  description: "API to read electronic product information"
  version: v1
paths:
  /Bundle:
    get:
      operationId: EP105
      summary: "Search Document"
      description: "Allows searching for documents that match various criteria. Several may be returned. Associated documents are not returned (unless _include is used)"
      parameters:
        - name: params
          in: query
          description: "Query parameters (e.g. /Bundle?composition.text=kaly)"
          schema:
            type: object
      responses:
        '200':
          description: "A set of matching items, as a searchset Bundle of document Bundles"
  /Bundle/{id}:
    get:
      operationId: EP102
      summary: "Get Document (read)"
      description: "Retrieve the latest copy of a single document"
      parameters:
        - name: id
          in: path
          required: true
          description: "Id of the document to retrieve"
          schema:
            type: string
      responses:
        '200':
          description: "A single document Bundle is returned, with the specified id, including the embedded Composition and List resources, and any Binary images"
  /Bundle/{id}/_history:
    get:
      operationId: EP107
      summary: "Get Document History"
      description: "Retrieve all previous copies of a single document (possibly that has been deleted)"
      parameters:
        - name: id
          in: path
          required: true
          description: "Id of the document to retrieve"
          schema:
            type: string
      responses:
        '200':
          description: "A set of document Bundles is returned - all the older versions of the requested id - including the embedded Composition and product List resources, and any Binary images"
  /Bundle/{id}/_history/{history-id}:
    get:
      operationId: EP106
      summary: "Get Document History Item"
      description: "Retrieve a previous copy of a single document (possibly that has been deleted)"
      parameters:
        - name: id
          in: path
          required: true
          description: "Id of the document to retrieve"
          schema:
            type: string
        - name: history-id
          in: path
          required: true
          description: "Id of the version to retrieve"
          schema:
            type: string
      responses:
        '200':
          description: "A single document Bundle is returned, with the specified id and history id, including the embedded Composition and product List resources, and any Binary images"

  /List:
    get:
      operationId: EP125
      summary: "Search Document Set"
      description: "Allows searching for document sets, by type, and by contents"
      parameters:
        - name: params
          in: query
          description: "Examples (can be combined): by contained document properties, by list type, date. TODO need full list of parameters and modes"
          schema:
            type: object
      responses:
        '200':
          description: "A set of matching items, as a searchset Bundle of Lists. Does not return the actual documents (though this may be possible via _include)."
  /List/{id}:
    get:
      operationId: EP122
      summary: "Get Document List (read)"
      description: "Get a single document List by a known id. Doesn't retrieve the documents themselves (unless _included, see also below Get Document Set)"
      parameters:
        - name: id
          in: path
          required: true
          description: "Id of the list to retrieve"
          schema:
            type: string
      responses:
        '200':
          description: "A document List"
  /List/{id}/_history:
    get:
      operationId: EP127
      summary: "Get Document List history"
      description: "Retrieve all previous copies of a given List"
      parameters:
        - name: id
          in: path
          required: true
          description: "Id of the list to retrieve"
          schema:
            type: string
      responses:
        '200':
          description: "A Bundle set of document Lists is returned"
  /List/{id}/_history/{history-id}:
    get:
      operationId: EP126
      summary: "Get Document List history Item"
      description: "Retrieve a previous copy of a List (possibly that has been deleted)"
      parameters:
        - name: id
          in: path
          required: true
          description: "Id of the list to retrieve"
          schema:
            type: string
        - name: history-id
          in: path
          required: true
          description: "Id of the version to retrieve"
          schema:
            type: string
      responses:
        '200':
          description: "A single document List is returned, with the specified id and history id"

components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]